In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [6]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [7]:
# Create our features
X = pd.get_dummies(df, columns=['home_ownership', 'verification_status', 'issue_d', 'pymnt_plan', 'initial_list_status', 
                               'next_pymnt_d', 'application_type', 'hardship_flag', 'debt_settlement_flag']).drop('loan_status', axis=1)


# Create our target
y = df['loan_status']

In [8]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [9]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [11]:
# Resample the training data with the BalancedRandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=28)
model = model.fit(X_train, y_train)

In [12]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

y_pred = model.predict(X_test)
acc_score = balanced_accuracy_score(y_test, y_pred)

In [13]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

cm_df = pd.DataFrame(
    cm, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"])

cm_df

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   28                  59
Actual Low Risk                    11               17107

In [14]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.72      0.32      1.00      0.44      0.57      0.30        87
   low_risk       1.00      1.00      0.32      1.00      0.57      0.34     17118

avg / total       1.00      1.00      0.33      1.00      0.57      0.34     17205

In [16]:
# List the features sorted in descending order by feature importance
features_rank = sorted(zip(model.feature_importances_, X.columns), reverse=True)
for feature in features_rank:
    print(f"{feature[1]}: ({feature[0]})")

total_rec_prncp: (0.0918637640682431)
total_rec_int: (0.0690470243984404)
last_pymnt_amnt: (0.06390428125918356)
total_pymnt: (0.06008384590181368)
total_pymnt_inv: (0.05404274308749965)
out_prncp_inv: (0.02058420626554387)
out_prncp: (0.019309983939565286)
mo_sin_old_rev_tl_op: (0.01857354212819049)
installment: (0.01850778636609307)
dti: (0.016187704212389152)
max_bal_bc: (0.015284918814626307)
mo_sin_old_il_acct: (0.015021162593021315)
total_rec_late_fee: (0.014781711605323059)
revol_bal: (0.01474994007412423)
annual_inc: (0.014494442813687624)
bc_open_to_buy: (0.014467817747481137)
bc_util: (0.014022206620086537)
total_bc_limit: (0.013969842773051277)
total_bal_ex_mort: (0.013924393828863024)
total_bal_il: (0.013708074037092064)
total_rev_hi_lim: (0.013383915438888458)
avg_cur_bal: (0.013303177431135097)
tot_hi_cred_lim: (0.01289815468598791)
loan_amnt: (0.01272498233091299)
tot_cur_bal: (0.012444362091723657)
total_acc: (0.011867983529999841)
total_il_high_credit_limit: (0.01149270639996577)
il_util: (0.011380482276158725)
mths_since_rcnt_il: (0.011057343505159382)
all_util: (0.010933152035973807)
mo_sin_rcnt_rev_tl_op: (0.010904683894952489)
mths_since_recent_inq: (0.01063774101180996)
mths_since_recent_bc: (0.010324746981525452)
int_rate: (0.010323999724676397)
num_il_tl: (0.01018529185394261)
issue_d_Mar-2019: (0.009704615070745869)
num_rev_tl_bal_gt_0: (0.009480174437293492)
num_actv_bc_tl: (0.009227666456212662)
num_sats: (0.009077684310735596)
num_actv_rev_tl: (0.008710740472488394)
total_cu_tl: (0.008706248276637036)
open_acc: (0.00847062840585882)
mo_sin_rcnt_tl: (0.008444321538020765)
num_bc_tl: (0.008438834128941529)
pct_tl_nvr_dlq: (0.008352417438995417)
num_rev_accts: (0.00820128833521966)
acc_open_past_24mths: (0.008197386938922337)
inq_last_12m: (0.008179791195956384)
open_rv_24m: (0.007296619136996666)
num_bc_sats: (0.007131968721425154)
open_il_24m: (0.007074191932504636)
num_tl_op_past_12m: (0.00675837091719749)
open_act_il: (0.006708101191667153)
inq_fi: (0.006671398263373957)
num_op_rev_tl: (0.006353349140143763)
percent_bc_gt_75: (0.006094621454226155)
mort_acc: (0.00598912960656375)
open_acc_6m: (0.005925157997088835)
issue_d_Feb-2019: (0.00581852509896815)
issue_d_Jan-2019: (0.005252502093775243)
open_rv_12m: (0.0050202588750236365)
open_il_12m: (0.004944782415517706)
next_pymnt_d_Apr-2019: (0.00469586852301284)
tot_coll_amt: (0.004348635235912167)
inq_last_6mths: (0.00414452795753092)
next_pymnt_d_May-2019: (0.003907821655454762)
num_accts_ever_120_pd: (0.003756178187904008)
delinq_2yrs: (0.003651138749208336)
home_ownership_OWN: (0.002449644876157241)
pub_rec_bankruptcies: (0.002119121770338134)
num_tl_90g_dpd_24m: (0.0019961961296044105)
pub_rec: (0.001954274052794744)
verification_status_Source Verified: (0.0018185754133384128)
verification_status_Verified: (0.001774473044668017)
home_ownership_RENT: (0.0015834667934377454)
application_type_Joint App: (0.0015091290816646123)
home_ownership_MORTGAGE: (0.0014617640590072654)
initial_list_status_f: (0.0014536480491999157)
collections_12_mths_ex_med: (0.001448777754980143)
initial_list_status_w: (0.0013769705601971258)
application_type_Individual: (0.00136640221086668)
verification_status_Not Verified: (0.0013655480410982035)
home_ownership_ANY: (0.0009986046672439907)
chargeoff_within_12_mths: (0.00019634360874862537)
tax_liens: (0.0)
recoveries: (0.0)
pymnt_plan_n: (0.0)
policy_code: (0.0)
num_tl_30dpd: (0.0)
num_tl_120dpd_2m: (0.0)
hardship_flag_N: (0.0)
delinq_amnt: (0.0)
debt_settlement_flag_N: (0.0)
collection_recovery_fee: (0.0)
acc_now_delinq: (0.0)

### Easy Ensemble AdaBoost Classifier

In [19]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
e_model = EasyEnsembleClassifier(n_estimators=100, random_state=1)
e_model.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [20]:
# Calculated the balanced accuracy score
y_pred = e_model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.925427358175101

In [21]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual High Risk", "Actual Low Risk"], columns=["Predicted High Risk", "Predicted Low Risk"])
cm_df

                  Predicted High Risk  Predicted Low Risk
Actual High Risk                   79                   8
Actual Low Risk                   979               16139

In [22]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.07      0.91      0.94      0.14      0.93      0.85        87
   low_risk       1.00      0.94      0.91      0.97      0.93      0.86     17118

avg / total       0.99      0.94      0.91      0.97      0.93      0.86     17205